language: python
python:
- '2.7'

before_install:
- pip install Inject==3.3.1
- pip install pysmi==0.0.6
- pip install pysnmp==4.3.1
- pip install traceback2==1.4.0
- pip install nose
- pip install coverage
- pip install unittest2
- pip install mock
- pip install teamcity-messages
- pip install jsonpickle
- pip install nose-exclude
- pip install -r test_requirements.txt -i https://testpypi.python.org/pypi

install:
    - python setup.py install

script: 
- python setup.py sdist --format zip
- python run_tests.py --with-coverage --cover-package=cloudshell

after_success:
    coveralls